jwt:

  secret: ${JWT_SECRET:minha-chave-secreta-super-longa-e-segura-para-api-prati-123}

  expiration: ${JWT_EXPIRATION:86400000}


spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true